export const fakeTableData = [
    {
        name: "Aiden Garcia",
        universe_size: 6472371,
        engaged_fans: 211861,
        fan_activity: 52,
        age: 53,
        in_market: false,
        country: "India",
        income: 31228,
        children_in_house: 0,
        ethnicity: "Caucasian",
    },
    {
        name: "Aria Anderson",
        universe_size: 1823723,
        engaged_fans: 282197,
        fan_activity: 83,
        age: 58,
        in_market: false,
        country: "UK",
        income: 76677,
        children_in_house: 3,
        ethnicity: "Asian",
    },
    {
        name: "Oliver Wright",
        universe_size: 1491963,
        engaged_fans: 314082,
        fan_activity: 81,
        age: 35,
        in_market: false,
        country: "Australia",
        income: 48168,
        children_in_house: 4,
        ethnicity: "Hispanic",
    },
    {
        name: "Liam White",
        universe_size: 1636018,
        engaged_fans: 323335,
        fan_activity: 43,
        age: 54,
        in_market: true,
        country: "UK",
        income: 84028,
        children_in_house: 4,
        ethnicity: "Hispanic",
    },
    {
        name: "Benjamin Martin",
        universe_size: 9732910,
        engaged_fans: 222029,
        fan_activity: 46,
        age: 18,
        in_market: false,
        country: "Germany",
        income: 83014,
        children_in_house: 0,
        ethnicity: "Asian",
    },
    {
        name: "Camila Lewis",
        universe_size: 6533942,
        engaged_fans: 393672,
        fan_activity: 44,
        age: 48,
        in_market: true,
        country: "Germany",
        income: 99375,
        children_in_house: 2,
        ethnicity: "Mixed",
    },
    {
        name: "Ethan Harris",
        universe_size: 8866382,
        engaged_fans: 129599,
        fan_activity: 77,
        age: 48,
        in_market: true,
        country: "Australia",
        income: 146486,
        children_in_house: 2,
        ethnicity: "Caucasian",
    },
    {
        name: "Michael Rodriguez",
        universe_size: 5648938,
        engaged_fans: 215450,
        fan_activity: 81,
        age: 35,
        in_market: true,
        country: "Canada",
        income: 116508,
        children_in_house: 1,
        ethnicity: "Asian",
    },
    {
        name: "Elijah Moore",
        universe_size: 2624857,
        engaged_fans: 102929,
        fan_activity: 18,
        age: 38,
        in_market: false,
        country: "Japan",
        income: 131268,
        children_in_house: 0,
        ethnicity: "Caucasian",
    },
    {
        name: "Grace Jackson",
        universe_size: 3818048,
        engaged_fans: 322631,
        fan_activity: 25,
        age: 26,
        in_market: true,
        country: "USA",
        income: 85041,
        children_in_house: 0,
        ethnicity: "Asian",
    },
    {
        name: "Emma Wilson",
        universe_size: 1948809,
        engaged_fans: 323756,
        fan_activity: 71,
        age: 49,
        in_market: true,
        country: "Canada",
        income: 105276,
        children_in_house: 4,
        ethnicity: "Caucasian",
    },
    {
        name: "Oliver Anderson",
        universe_size: 5868506,
        engaged_fans: 126357,
        fan_activity: 97,
        age: 41,
        in_market: true,
        country: "USA",
        income: 38231,
        children_in_house: 1,
        ethnicity: "Mixed",
    },
    {
        name: "Benjamin Miller",
        universe_size: 6490762,
        engaged_fans: 338066,
        fan_activity: 53,
        age: 63,
        in_market: true,
        country: "UK",
        income: 95773,
        children_in_house: 0,
        ethnicity: "Black",
    },
    {
        name: "Sebastian White",
        universe_size: 8827071,
        engaged_fans: 472687,
        fan_activity: 6,
        age: 30,
        in_market: true,
        country: "France",
        income: 86809,
        children_in_house: 0,
        ethnicity: "Black",
    },
    {
        name: "Isabella Clark",
        universe_size: 9229453,
        engaged_fans: 88530,
        fan_activity: 60,
        age: 55,
        in_market: true,
        country: "Germany",
        income: 39103,
        children_in_house: 3,
        ethnicity: "Black",
    },
    {
        name: "Ethan Lee",
        universe_size: 2757840,
        engaged_fans: 154689,
        fan_activity: 67,
        age: 63,
        in_market: false,
        country: "Japan",
        income: 41118,
        children_in_house: 2,
        ethnicity: "Black",
    },
    {
        name: "Jackson Robinson",
        universe_size: 7511652,
        engaged_fans: 88820,
        fan_activity: 54,
        age: 32,
        in_market: false,
        country: "Canada",
        income: 73489,
        children_in_house: 2,
        ethnicity: "Hispanic",
    },
    {
        name: "Ethan Taylor",
        universe_size: 7912814,
        engaged_fans: 167919,
        fan_activity: 100,
        age: 23,
        in_market: false,
        country: "UK",
        income: 56757,
        children_in_house: 3,
        ethnicity: "Caucasian",
    },
];
